global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['173.82.181.149:9090']

  - job_name: 'gateway-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ['173.82.181.149:8080']

  - job_name: 'user-crud-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: [ '173.82.181.149:8082' ]

  - job_name: 'user-ui-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ['173.82.181.149:8081']

  - job_name: 'i18n-actuator'
    metrics_path: "actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: [ '173.82.181.149:8083' ]
  
  - job_name: node
    static_configs:
      - targets: ['173.82.181.149:9100']
  
  - job_name: node-ziling
    static_configs:
      - targets: ['129.146.241.107:9100'] 

  - job_name: node-ziling2
    static_configs:
      - targets: ['208.162.40.55:9100'] 

  - job_name: node-annie
    static_configs:
      - targets: ['168.138.68.166:9100'] 
