server:
  port: 8084

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/laneyang/Micro-Service.git
          search-paths: service-configs
          default-label: docker
          # uri: ${HOME}/Developer/SpringCloud/user-start/service-configs

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-services:8085/eureka/
